### ISSUE TITLE
Prepare for June 3rd 

### ISSUE THREAD

**Issue by jhoguet** [burlingtonjs/js-usergroup-rampup#1]
- [x] create a repo
- [x] add Donnie, Payton, Matt, Ian as collaborators
- [x] create topic pages 
- [x] bitly links from main page to topic pages so that people can more easily type the url they see on the projector
- [x] change name to emphasize knowledge share
- [x] announcement to let people know the topics and that we need mentors too (share your knowledge)
- [x] stamp out one of the topics so that others can use it as a baseline

Add Goals / Exercises for
- [x] new to programming 
- [x] new to javascript
- [x] js in node 
- [x] document object model
- [x] array methods
- [x] objects and inheritance
- [x] callbacks and promises

**Comment by sirbrillig** [comment]
I added some exercises for Objects and the DOM. Feel free to modify them as you see fit. Also I had [a question](https://github.com/burlingtonjs/js-usergroup-rampup/commit/db95047bd86e7e0ba4dfad3b29b085556030a9c4#commitcomment-11412117) about the setup for the Array exercises which might be a bug or it might be intentional. I wasn't sure.

**Comment by jhoguet** [comment]
FYI donnie is working on the promises one

**Comment by mattparrilla** [comment]
I'll try my hand at "new to programming"

**Comment by jhoguet** [comment]
working on new to js

**Comment by jhoguet** [comment]
new to js is done. Looking into new to node

**Comment by donnie-coleman** [comment]
I'm still working hard on callbacks and promises. I'll have something for everyone to look at tomorrow.

**Comment by jhoguet** [comment]
@donnietron awesome

**Comment by jhoguet** [comment]
slapped something together for node - don't love the format of nodeschool, but google was funneling me there so it much be good...

**Comment by donnie-coleman** [comment]
I have a callback-heck starting example that I've created in JSfiddle using VanillaJS. 

http://jsfiddle.net/donniec/deu612bq/7/

I've been struggling with how to make this example truly callback hell. I plan to shorten the list of students and have the code make a second ajax call out to get grades for each student in the list. Any other ideas?

The idea is that we'll transform this example by using native `Promises` and in the process we'll get the ability to do some cool stuff like show the list of students in order without having to wait for each ajax request to return in order.

What do you think?

**Comment by mattparrilla** [comment]
@jhoguet I didn't bother adding anything to new-to-programming from new-to-js. I went through the new-to-programming module during lunch and I certainly can't create anything better/more basic than that.

I removed the extra challenge as the link provided contains much more content than a true beginner could work through in a day, let alone an hour.

**Comment by jhoguet** [comment]
Great work and thanks for the help.
