### ISSUE TITLE
Prep for November Ramp up

### ISSUE THREAD

**Issue by jhoguet** [burlingtonjs/js-usergroup-rampup#6]
Meet Wednesday the 28th 5 - 7 at Citizen Cider to prepare for the ramp up on November 4th. 

Goals are 
- [x] identify mentors for some topics so there is less risk the day of that we don't have enough mentors
- [x] identify any last minute changes to the protocol / challenges to get the most out of the meetup
- [x] identify who / what administrative things need to get done ahead of time (eg. print outs)
- [x] identify who is going to man the door

**Comment by jhoguet** [comment]
please comment here letting us know who is coming on Oct 28th

can only make it for one hour - that is fine - we made it two hours so that you could come when works for you.

**Comment by mattparrilla** [comment]
I've got a conflict, though I'll possibly be able to make it for some of the time.

**Comment by donnie-coleman** [comment]
I'll be there

**Comment by sirbrillig** [comment]
I can be there, but I might be cutting it close to 5pm.

**Comment by dangeranger** [comment]
I'll work to be there around 5:00-5:30.

**Comment by jhoguet** [comment]
printed off 12 topic sheets

[topics.pdf](https://github.com/burlingtonjs/js-usergroup-rampup/files/24942/topics.pdf)

**Comment by jhoguet** [comment]
early volunteers: 

Payton - Objects
Josh - new to js or new to programming
~~Nick - node (had a conflict)~~
Donnie - promises

Jon volunteered to be the doorman again, but will pick someone else to take over part way through... no one wants to be the doorman :)

we should be all set now - thanks to all for meeting and helping work out the last minute details
